version: "3.9"
services:
  db:
    image: postgres:14.2-alpine
    env_file: .env
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - data:/data

  cache:
    image: "redis:alpine"
    env_file: .env
    command: redis-server --requirepass $REDIS_PASSWORD --maxmemory $REDIS_MAXMEMORY --maxmemory-policy $REDIS_MAXMEMORY_POLICY --port $REDIS_PORT
    restart: always
    ports:
      - $REDIS_PORT:$REDIS_PORT
    volumes:
      - cache:/var/lib/redis

  rabbitmq:
    image: rabbitmq:3.9.13-alpine
    env_file: .env
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_PORT
      - $RABBITMQ_MANAGEMENT_PORT:$RABBITMQ_MANAGEMENT_PORT

  app:
    container_name: node_postgres_rest_framework
    env_file: .env
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - $PORT:$PORT
    depends_on:
      - db
      - cache
      - rabbitmq
    stdin_open: true
    tty: true

volumes:
  data:
  cache:
